// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOWhy8aNb2VZNs1nyIcGdERIbDg4XLJP8',
    appId: '1:659003870914:web:d01793873644438c28755b',
    messagingSenderId: '659003870914',
    projectId: 'pixel-76562',
    authDomain: 'pixel-76562.firebaseapp.com',
    storageBucket: 'pixel-76562.firebasestorage.app',
    measurementId: 'G-GXZM4YMBYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB73CkF90A0kW1gjejfTLanCfdNHhSXNG4',
    appId: '1:659003870914:android:40171be78887243a28755b',
    messagingSenderId: '659003870914',
    projectId: 'pixel-76562',
    storageBucket: 'pixel-76562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUIvGnT1c7yhzhf7I6JmLYYjngpolou7M',
    appId: '1:659003870914:ios:6ad2728565ae098728755b',
    messagingSenderId: '659003870914',
    projectId: 'pixel-76562',
    storageBucket: 'pixel-76562.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUIvGnT1c7yhzhf7I6JmLYYjngpolou7M',
    appId: '1:659003870914:ios:6ad2728565ae098728755b',
    messagingSenderId: '659003870914',
    projectId: 'pixel-76562',
    storageBucket: 'pixel-76562.firebasestorage.app',
    iosBundleId: 'com.example.safewalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOWhy8aNb2VZNs1nyIcGdERIbDg4XLJP8',
    appId: '1:659003870914:web:d80f0d45d5bb144428755b',
    messagingSenderId: '659003870914',
    projectId: 'pixel-76562',
    authDomain: 'pixel-76562.firebaseapp.com',
    storageBucket: 'pixel-76562.firebasestorage.app',
    measurementId: 'G-6PTZ3WMBRW',
  );
}
